version: '3.5'


networks:
  farmacia-network:


volumes:
  mysql-db:

services:
  mysql:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_DATABASE: 'farmacia'
      MYSQL_ROOT_PASSWORD: 'secretapacas'
    ports:
      - "3306:3306"
    networks:
      - farmacia-network
    volumes:
      - mysql-db:/var/lib/mysql

  farmacia-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: farmacia:latest
    container_name: farmacia
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - farmacia-network
